### ISSUE TITLE
missing file gc.h

### ISSUE THREAD

**Issue by barak** [luvisi/continuinglogo#1]
```
$ ./configure
...
$ make
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c interpreter.c
In file included from list_memory.h:50,
                 from interpreter.c:27:
structures.h:22:10: fatal error: gc.h: No such file or directory
 #include "gc.h"
          ^~~~~~
compilation terminated.
Makefile:39: recipe for target 'interpreter.o' failed
make: *** [interpreter.o] Error 1

```

**Comment by luvisi** [comment]
You seem to be using an old copy of structures.h or declarations.pl.  The current version includes "pcgc.h" and not "gc.h"

I'm not sure what happened.  Did you do a git clone or did you download the latest release?

Andru

**Comment by barak** [comment]
This is the tip of the github repo master branch, tag 0.005, and I'm running Debian GNU/Linux.
````
$ git remote -v show 
origin	https://github.com/luvisi/continuinglogo (fetch)
origin	ssh://git@github.com/luvisi/continuinglogo (push)

$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

$ git show-ref HEAD master 0.005
c519a3f36a896e8e75b93bdeb51ddffabddd0dbc refs/heads/master
c519a3f36a896e8e75b93bdeb51ddffabddd0dbc refs/remotes/origin/HEAD
c519a3f36a896e8e75b93bdeb51ddffabddd0dbc refs/remotes/origin/master
c519a3f36a896e8e75b93bdeb51ddffabddd0dbc refs/tags/0.005

$ ./configure
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking for main in -lm... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking limits.h usability... yes
checking limits.h presence... yes
checking for limits.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking termios.h usability... yes
checking termios.h presence... yes
checking for termios.h... yes
checking for unistd.h... (cached) yes
checking for stdbool.h that conforms to C99... yes
checking for _Bool... yes
checking for inline... inline
checking for size_t... yes
checking for pid_t... yes
checking vfork.h usability... no
checking vfork.h presence... no
checking for vfork.h... no
checking for fork... yes
checking for vfork... yes
checking for working fork... yes
checking for working vfork... (cached) yes
checking for stdlib.h... (cached) yes
checking for GNU libc compatible malloc... yes
checking for working strtod... yes
checking for dup2... yes
checking for pow... yes
checking for sqrt... yes
checking for strcasecmp... yes
checking for strchr... yes
checking for strerror... yes
checking for strncasecmp... yes
checking for strspn... yes
checking for strstr... yes
configure: creating ./config.status
config.status: creating Makefile
config.status: creating config.h

$ wx-config --cxx --cxxflags
g++
-I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread

$ make -j1
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c audio.cpp
audio.cpp: In member function ‘virtual void* RecordingThread::Entry()’:
audio.cpp:661:19: warning: enumeration value ‘SILENCE_LOGGING’ not handled in switch [-Wswitch]
             switch(command.command) {
                   ^
audio.cpp:593:9: warning: unused variable ‘dtmf_times_seen’ [-Wunused-variable]
     int dtmf_times_seen = 0, dtmf_min_seen = 1;
         ^~~~~~~~~~~~~~~
audio.cpp:593:30: warning: unused variable ‘dtmf_min_seen’ [-Wunused-variable]
     int dtmf_times_seen = 0, dtmf_min_seen = 1;
                              ^~~~~~~~~~~~~
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c ms_gc.c
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c interpreter.c
In file included from list_memory.h:50,
                 from interpreter.c:27:
structures.h:22:10: fatal error: gc.h: No such file or directory
 #include "gc.h"
          ^~~~~~
compilation terminated.
Makefile:39: recipe for target 'interpreter.o' failed
make: *** [interpreter.o] Error 1

$ git grep -n 'include.*"gc'
structures.h:22:#include "gc.h"

$ git blame -- structures.h | egrep 'gc[.]h'
c519a3f3 (Andru Luvisi 2017-01-12 07:24:27 -0800  22) #include "gc.h"
````

**Comment by luvisi** [comment]
Ok.  Somehow I had an old version of structures.[ch] in the repository.  I just regenerated them with declarations.pl.  It should work now.  It's not well documented, but you'll also need wxWidgets, portaudio, and libgc.  Although it currently uses a copying collector by default, the plumbing was sort of there for using a conservative collector.

**Comment by barak** [comment]
Even with running `./declarations.pl` and `apt install libgc-dev portaudio19-dev` issues remain:
````
$ ./declarations.pl
$ ./configure
$ make -k -j1
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c list_memory.c
list_memory.c: In function ‘sexpr* list_to_array(IC*, sexpr*, int)’:
list_memory.c:1134:16: error: reference to ‘array’ is ambiguous
     sexpr *a = array(ic, length, origin);
                ^~~~~
In file included from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/bits/stl_map.h:63,
                 from /usr/include/c++/8/map:61,
                 from turtles.h:5,
                 from wxui.h:37,
                 from interpreter.h:26,
                 from list_memory.h:24,
                 from list_memory.c:21:
/usr/include/c++/8/array:94:12: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> struct std::array’
     struct array
            ^~~~~
list_memory.c:1105:8: note:                 ‘sexpr* array(IC*, int, int)’
 sexpr *array(IC *ic, int length, int origin) {
        ^~~~~
Makefile:39: recipe for target 'list_memory.o' failed
make: *** [list_memory.o] Error 1
`wx-config --cxx --cxxflags` -g -Wall -O3 -fno-align-functions   -DLIBRARYDIR=\"/usr/local/share/continuinglogo\" -I. -c global_environment.c
global_environment.c: In function ‘sexpr* array_subr(IC*, sexpr*)’:
global_environment.c:2455:12: error: reference to ‘array’ is ambiguous
     return array(ic, length, origin);
            ^~~~~
In file included from /usr/include/c++/8/tuple:39,
                 from /usr/include/c++/8/bits/stl_map.h:63,
                 from /usr/include/c++/8/map:61,
                 from turtles.h:5,
                 from wxui.h:37,
                 from interpreter.h:26,
                 from global_environment.h:24,
                 from global_environment.c:50:
/usr/include/c++/8/array:94:12: note: candidates are: ‘template<class _Tp, long unsigned int _Nm> struct std::array’
     struct array
            ^~~~~
In file included from global_environment.h:26,
                 from global_environment.c:50:
list_memory.h:291:8: note:                 ‘sexpr* array(IC*, int, int)’
 sexpr *array(IC *ic, int length, int origin);
        ^~~~~
Makefile:39: recipe for target 'global_environment.o' failed
make: *** [global_environment.o] Error 1
make: Target 'all' not remade because of errors.
````

**Comment by luvisi** [comment]
I see that I was lazy and put "use namespace std" in wxui.h.  I took that out, and added std:: in a couple of places so I don't need it.  Clearly we're using different versions of gcc.

Please pull the latest version and try again.  Thank you so much for your patience!

Andru

**Comment by barak** [comment]
Now it compiles! And runs!

On the other hand:
````
? forward 100
I don't know how to forward in Top Level at:
[forward 100]
````
But I supposed this is a new issue...

**Comment by luvisi** [comment]
Did you do a "make install" before running clogo?  That looks like it didn't read the initialization file.

**Comment by barak** [comment]
that was it, stupid of me; thanks
